# Generated by Django 5.0.3 on 2024-03-14 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feather_color', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bird_photos')),
            ],
        ),
        migrations.CreateModel(
            name='BirdSaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saw', models.DateTimeField(auto_now_add=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_birds.bird')),
            ],
        ),
    ]
